# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Use the latest stable version of black
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
        additional_dependencies: [ prettier@2.3.2 ]
        files: \.(js|css)$

  - repo: https://github.com/motet-a/jinjalint
    rev: master # select a tag / sha to point at
    hooks:
      - id: jinjalint
        types: [ file ]  # restore the default `types` matching
        files: \.(html|sls)$