"""Delete unused fields in user table

Revision ID: 07dbe8ea43a9
Revises: 435f935a4f13
Create Date: 2024-05-17 01:12:14.429111

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07dbe8ea43a9"
down_revision = "435f935a4f13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_failed_login")
        batch_op.drop_column("failed_login_attempts")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("failed_login_attempts", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_failed_login", sa.DATETIME(), nullable=True)
        )

    # ### end Alembic commands ###
