"""Remove redundant field from the Guess table

Revision ID: 435f935a4f13
Revises: 9c02e3bc5899
Create Date: 2024-05-14 22:12:13.427615

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "435f935a4f13"
down_revision = "9c02e3bc5899"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guess", schema=None) as batch_op:
        batch_op.drop_column("points_for_guesser")
        batch_op.drop_column("points_for_creator")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guess", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("points_for_creator", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("points_for_guesser", sa.INTEGER(), nullable=True)
        )

    # ### end Alembic commands ###
