"""Change the names of some attributes in Guess model for easier understanding

Revision ID: 7e4adebcbbd4
Revises: d597fbf56cec
Create Date: 2024-05-11 23:54:51.074144

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e4adebcbbd4"
down_revision = "d597fbf56cec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guess", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("guessed_word", sa.String(length=255), nullable=False)
        )
        batch_op.add_column(sa.Column("guessed_at", sa.DateTime(), nullable=True))
        batch_op.drop_column("time_guessed")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guess", schema=None) as batch_op:
        batch_op.add_column(sa.Column("time_guessed", sa.DATETIME(), nullable=True))
        batch_op.drop_column("guessed_at")
        batch_op.drop_column("guessed_word")

    # ### end Alembic commands ###
