"""Add columns to the User model to track failed login attempts

Revision ID: 9c02e3bc5899
Revises: 7e4adebcbbd4
Create Date: 2024-05-09 19:30:09.102077

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c02e3bc5899"
down_revision = "7e4adebcbbd4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_failed_login", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("failed_login_attempts", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("failed_login_attempts")
        batch_op.drop_column("last_failed_login")

    # ### end Alembic commands ###
